[tox]
envlist = py310
skipsdist = True

[testenv]
deps =
    pytest
    pytest-cov
commands =
    pytest tests/unittest --cov=src/fldt --cov-report=term-missing --cov-report=xml:coverage.xml --cov-branch